"""Updating models

Revision ID: 34b6b55e0c8d
Revises: 6645acd0c131
Create Date: 2023-10-01 16:24:30.581821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b6b55e0c8d'
down_revision = '6645acd0c131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
