"""Updating models

Revision ID: 4f3f291b7cef
Revises: 33b780396f6e
Create Date: 2023-10-30 17:55:31.231830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3f291b7cef'
down_revision = '33b780396f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('daily_request_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_request_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_request_time')
        batch_op.drop_column('daily_request_count')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
