"""Updating models

Revision ID: 95efe42c0913
Revises: c049320dc395
Create Date: 2023-11-05 00:20:23.842225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95efe42c0913'
down_revision = 'c049320dc395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('confirm_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirm_sent_at')
        batch_op.drop_column('confirmation_token')
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
