"""Updating models

Revision ID: a278e3306899
Revises: 95efe42c0913
Create Date: 2023-11-06 22:11:59.990526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a278e3306899'
down_revision = '95efe42c0913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
